[package]
name = "test-tonic"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.45", features = ["parking_lot", "rt-multi-thread", "macros", "io-util"] }

[build-dependencies]
tonic-build = "0.11"
